/**
 * NEMT Platform - Mock Users Data
 * 25 个模拟交易者用户数据
 */

export interface MockUser {
  id: string;
  name: string;
  avatar: string;
  bio: string;
  strategiesCount: number;
  followers: number;
  rating: number;
  totalPnl: number;
  winRate: number;
  specialties: string[];
  joinDate: string;
}

// 头像颜色池
const AVATAR_COLORS = [
  '#6b21a8', '#7c3aed', '#8b5cf6', '#a855f7', '#c084fc',
  '#0891b2', '#0e7490', '#06b6d4', '#22c55e', '#16a34a',
  '#eab308', '#ca8a04', '#f97316', '#ea580c', '#ef4444',
  '#ec4899', '#db2777', '#f43f5e', '#8b5cf6', '#6366f1',
];

export const MOCK_USERS: MockUser[] = [
  {
    id: 'user_1',
    name: '网格大师',
    avatar: AVATAR_COLORS[0],
    bio: '专注网格交易策略5年，擅长震荡行情套利，年化收益稳定在40%+',
    strategiesCount: 12,
    followers: 3421,
    rating: 4.9,
    totalPnl: 128500,
    winRate: 78.5,
    specialties: ['网格交易', '震荡策略', '套利'],
    joinDate: '2021-03-15',
  },
  {
    id: 'user_2',
    name: '趋势猎手',
    avatar: AVATAR_COLORS[1],
    bio: '多周期趋势跟踪专家，擅长大趋势捕捉，曾在2023年抓住BTC 3倍行情',
    strategiesCount: 8,
    followers: 2847,
    rating: 4.8,
    totalPnl: 95600,
    winRate: 65.2,
    specialties: ['趋势跟踪', '多周期分析', '止损策略'],
    joinDate: '2020-08-22',
  },
  {
    id: 'user_3',
    name: '套利王',
    avatar: AVATAR_COLORS[2],
    bio: '跨交易所套利专家，捕捉价差利润，日均套利收益2%-5%',
    strategiesCount: 6,
    followers: 1923,
    rating: 4.7,
    totalPnl: 87600,
    winRate: 89.3,
    specialties: ['三角套利', '跨所套利', '资金费率'],
    joinDate: '2021-06-10',
  },
  {
    id: 'user_4',
    name: '高频之神',
    avatar: AVATAR_COLORS[3],
    bio: '高频算法交易，延迟优化专家，毫秒级响应',
    strategiesCount: 4,
    followers: 1534,
    rating: 4.6,
    totalPnl: 65400,
    winRate: 72.1,
    specialties: ['高频交易', '做市', '延迟优化'],
    joinDate: '2020-11-05',
  },
  {
    id: 'user_5',
    name: '做市商A',
    avatar: AVATAR_COLORS[4],
    bio: '专业做市策略开发，API交易专家，为多个交易所提供流动性',
    strategiesCount: 9,
    followers: 987,
    rating: 4.5,
    totalPnl: 54300,
    winRate: 68.9,
    specialties: ['做市策略', '订单簿分析', '流动性提供'],
    joinDate: '2021-01-20',
  },
  {
    id: 'user_6',
    name: '布林带女王',
    avatar: AVATAR_COLORS[5],
    bio: '统计学背景，专注布林带均值回归策略，量化模型优化专家',
    strategiesCount: 7,
    followers: 2341,
    rating: 4.8,
    totalPnl: 78900,
    winRate: 71.4,
    specialties: ['布林带', '均值回归', '统计套利'],
    joinDate: '2021-04-18',
  },
  {
    id: 'user_7',
    name: '波浪理论家',
    avatar: AVATAR_COLORS[6],
    bio: '艾略特波浪理论实践者，结合技术指标捕捉转折点',
    strategiesCount: 5,
    followers: 1234,
    rating: 4.4,
    totalPnl: 45600,
    winRate: 58.7,
    specialties: ['波浪理论', '技术分析', '反转策略'],
    joinDate: '2022-02-08',
  },
  {
    id: 'user_8',
    name: '对冲基金经理',
    avatar: AVATAR_COLORS[7],
    bio: '多策略组合管理，控制回撤，追求稳健收益',
    strategiesCount: 15,
    followers: 3421,
    rating: 4.9,
    totalPnl: 156700,
    winRate: 73.2,
    specialties: ['多策略组合', '对冲', '风控'],
    joinDate: '2020-05-12',
  },
  {
    id: 'user_9',
    name: '币圈老韭菜',
    avatar: AVATAR_COLORS[8],
    bio: '从韭菜到镰刀的蜕变，丰富的实盘经验总结',
    strategiesCount: 11,
    followers: 876,
    rating: 4.3,
    totalPnl: 32400,
    winRate: 62.5,
    specialties: ['趋势跟随', '波段交易', '实战经验'],
    joinDate: '2019-09-01',
  },
  {
    id: 'user_10',
    name: '量化新人',
    avatar: AVATAR_COLORS[9],
    bio: '刚入行的量化开发者，持续学习进步中',
    strategiesCount: 3,
    followers: 234,
    rating: 4.1,
    totalPnl: 8900,
    winRate: 55.3,
    specialties: ['Python量化', '学习进阶'],
    joinDate: '2023-11-15',
  },
  {
    id: 'user_11',
    name: '机器学习Quant',
    avatar: AVATAR_COLORS[10],
    bio: '用AI和机器学习预测市场走向，Python/PyTorch开发者',
    strategiesCount: 6,
    followers: 1567,
    rating: 4.6,
    totalPnl: 67800,
    winRate: 67.8,
    specialties: ['机器学习', '深度学习', '特征工程'],
    joinDate: '2021-08-20',
  },
  {
    id: 'user_12',
    name: '波动率猎手',
    avatar: AVATAR_COLORS[11],
    bio: '专注波动率交易，在VIX暴涨暴跌中寻找机会',
    strategiesCount: 4,
    followers: 789,
    rating: 4.4,
    totalPnl: 41200,
    winRate: 64.2,
    specialties: ['波动率交易', '期权策略', 'VIX'],
    joinDate: '2022-05-10',
  },
  {
    id: 'user_13',
    name: 'CTA策略王',
    avatar: AVATAR_COLORS[12],
    bio: '商品交易顾问背景，专注趋势型CTA策略',
    strategiesCount: 8,
    followers: 2134,
    rating: 4.7,
    totalPnl: 89700,
    winRate: 59.6,
    specialties: ['CTA策略', '趋势期货', '商品交易'],
    joinDate: '2020-12-01',
  },
  {
    id: 'user_14',
    name: '搬砖达人',
    avatar: AVATAR_COLORS[13],
    bio: '数字货币搬砖专家，7x24小时自动执行套利',
    strategiesCount: 5,
    followers: 1456,
    rating: 4.5,
    totalPnl: 56700,
    winRate: 91.2,
    specialties: ['搬砖套利', '跨平台', '自动交易'],
    joinDate: '2021-02-14',
  },
  {
    id: 'user_15',
    name: '合约对冲侠',
    avatar: AVATAR_COLORS[14],
    bio: '永续合约与现货对冲，追求无风险收益',
    strategiesCount: 6,
    followers: 1678,
    rating: 4.6,
    totalPnl: 72300,
    winRate: 85.4,
    specialties: ['合约对冲', '无风险套利', '资金费率'],
    joinDate: '2021-07-22',
  },
  {
    id: 'user_16',
    name: 'K线形态师',
    avatar: AVATAR_COLORS[15],
    bio: '专注K线形态识别，Pin Bar、吞没形态实战派',
    strategiesCount: 9,
    followers: 987,
    rating: 4.3,
    totalPnl: 34500,
    winRate: 61.8,
    specialties: ['K线形态', 'Pin Bar', '技术分析'],
    joinDate: '2022-09-05',
  },
  {
    id: 'user_17',
    name: '量化诗人',
    avatar: AVATAR_COLORS[16],
    bio: '用诗意的眼光看待市场，量化与哲学结合',
    strategiesCount: 7,
    followers: 654,
    rating: 4.2,
    totalPnl: 28700,
    winRate: 56.7,
    specialties: ['多策略', '哲学思维', '稳健交易'],
    joinDate: '2023-01-18',
  },
  {
    id: 'user_18',
    name: '日内交易员',
    avatar: AVATAR_COLORS[17],
    bio: '专注数字货币日内交易，每日稳定盈利目标',
    strategiesCount: 4,
    followers: 2134,
    rating: 4.7,
    totalPnl: 45600,
    winRate: 72.5,
    specialties: ['日内交易', '超短线', '止损纪律'],
    joinDate: '2021-10-30',
  },
  {
    id: 'user_19',
    name: '量化矿工',
    avatar: AVATAR_COLORS[18],
    bio: '挖掘数据中的Alpha因子，数据驱动型交易者',
    strategiesCount: 11,
    followers: 1234,
    rating: 4.5,
    totalPnl: 58900,
    winRate: 68.3,
    specialties: ['因子挖掘', '数据分析', '机器学习'],
    joinDate: '2021-05-25',
  },
  {
    id: 'user_20',
    name: '风控大师',
    avatar: AVATAR_COLORS[19],
    bio: '把风险控制放在第一位，追求长期稳健收益',
    strategiesCount: 8,
    followers: 1789,
    rating: 4.8,
    totalPnl: 92300,
    winRate: 75.6,
    specialties: ['风控管理', '仓位控制', '多策略'],
    joinDate: '2020-07-15',
  },
  {
    id: 'user_21',
    name: '山寨币猎手',
    avatar: AVATAR_COLORS[0],
    bio: '专注小市值山寨币，捕捉百倍潜力币',
    strategiesCount: 6,
    followers: 876,
    rating: 4.1,
    totalPnl: 23400,
    winRate: 45.2,
    specialties: ['山寨币', '潜力币挖掘', '高风险高收益'],
    joinDate: '2022-11-08',
  },
  {
    id: 'user_22',
    name: '量化教练',
    avatar: AVATAR_COLORS[1],
    bio: '帮助新手入门量化交易，分享策略设计思路',
    strategiesCount: 14,
    followers: 2567,
    rating: 4.9,
    totalPnl: 67800,
    winRate: 69.8,
    specialties: ['教学', '策略设计', '入门指南'],
    joinDate: '2020-04-20',
  },
  {
    id: 'user_23',
    name: '数字黄金猎人',
    avatar: AVATAR_COLORS[2],
    bio: '专注BTC/ETH趋势交易，捕捉大周期行情',
    strategiesCount: 5,
    followers: 3421,
    rating: 4.8,
    totalPnl: 134500,
    winRate: 63.4,
    specialties: ['BTC', 'ETH', '趋势交易'],
    joinDate: '2019-12-10',
  },
  {
    id: 'user_24',
    name: '期权策略师',
    avatar: AVATAR_COLORS[3],
    bio: '期权组合策略专家，构建复杂收益结构',
    strategiesCount: 7,
    followers: 654,
    rating: 4.4,
    totalPnl: 38700,
    winRate: 70.2,
    specialties: ['期权策略', '收益结构', '波动率对冲'],
    joinDate: '2022-03-15',
  },
  {
    id: 'user_25',
    name: 'DeFi套利者',
    avatar: AVATAR_COLORS[4],
    bio: '链上DeFi协议套利，捕捉链上价差机会',
    strategiesCount: 6,
    followers: 1123,
    rating: 4.5,
    totalPnl: 56700,
    winRate: 82.1,
    specialties: ['DeFi', '链上套利', 'MEV'],
    joinDate: '2022-06-28',
  },
];

// 辅助函数
export function getUserById(id: string): MockUser | undefined {
  return MOCK_USERS.find(u => u.id === id);
}

export function getTopRatedUsers(limit: number = 5): MockUser[] {
  return [...MOCK_USERS].sort((a, b) => b.rating - a.rating).slice(0, limit);
}

export function getTopFollowedUsers(limit: number = 5): MockUser[] {
  return [...MOCK_USERS].sort((a, b) => b.followers - a.followers).slice(0, limit);
}

export function getUsersBySpecialty(specialty: string): MockUser[] {
  return MOCK_USERS.filter(u => u.specialties.includes(specialty));
}
